package roboter;

public enum State {

	IDLE, UNLOAD, LOAD, 
	
	FAHR_ZUR_COMPANY_WEG_VORAUS,
	FAHR_ZUR_COMPANY_WEG_RECHTS,
	FAHR_ZUR_COMPANY_WEG_LINKS,
	
	FIND_LOADING_ZONE_WEG_VORAUS,
	FIND_LOADING_ZONE_WEG_LINKS,
	FIND_LOADING_ZONE_WEG_RECHTS,
	
	RUMDREHN,
	;
	
}
